# Generated by Django 3.1.1 on 2021-01-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='musics/'),
        ),
    ]
