# Generated by Django 3.1.1 on 2021-02-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210129_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='song_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='musics/'),
        ),
    ]
