# Generated by Django 3.1.1 on 2021-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20210202_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='song_image',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/images/default.png', null=True, upload_to='images/'),
        ),
    ]
